#!/usr/bin/env bash
#SBATCH --array=1-442%40                           # 442 jobs that run
#SBATCH --job-name=post_proc                       # base job name for the array
#SBATCH --mem-per-cpu=1000M                        # maximum 2250MMB per job
#SBATCH --time=0:10:00                             # maximum walltime per job
#SBATCH --nodes=1                                  # Only one node is needed
#SBATCH --ntasks=1                                 # These are serial jobs
#SBATCH --mail-type=ALL                            # send all mail (way to much)
#SBATCH --mail-user=andrew.d.nolan@maine.edu       # email to spend updates too
#SBATCH --output=logs/post_proc.out                # standard output
#SBATCH --error=logs/post_proc.err                 # standard error
# in the previous two lines %A" is replaced by jobID and "%a" with the array index



count=1
# loop over the mass balance offsets
for offset in $(seq -w $MB_0 $MB_s $MB_f); do
  # loop over mean annual air temps
  for T_ma in $(seq -w -9.00 0.1 -7.00); do
    # check if counter equals SLURM_ARRAY_TASK_ID
    if [[ $count -eq $SLURM_ARRAY_TASK_ID ]]; then
        break 2
    fi
    count=$((count+1))
  done
done

KEY='glc1-a'
dx=50
dt=1.0
NT=2000
TT=2000
# limit to 10 S.S. itters for transient runs
SS_itters=10
# diagnostic run is now restart variable
RESTART="${run_name}.result"
# prognostic run name
run_name="${KEY}_dx_${dx}_NT_${NT}_dt_${dt}_MB_${offset}_OFF_Tma_${T_ma}_prog"

file="${KEY}/nc/${run_name}.nc"

if [[ ! -f "${file/.nc/_gridded.nc}" ]]; then
  python3 grid_data.py $file

  echo
  echo $(basename $file) processed
  echo
fi
