name: thermal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ipython
  - pint
  - scipy
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - pip
  - xarray
  - netCDF4
  - h5netcdf
  - matplotlib
  - dask
  - dask-jobqueue
  - jupyterlab
  - rise
  - pip:
    - SALib
    - sshuttle
