name: thermal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ipython
  - pint
  - scipy
  - numpy
  - pandas
  - seaborn
  - pip
  - xarray 
  - matplotlib
  - dask
  - dask-jobqueue
  - jupyterlab
  - pip:
    - SALib
