name: thermal
channels:
  - conda-forge
dependencies:
  - python=3.9.6
  - ipython
  - pint
  - scipy
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - pip
  - xarray
  - netCDF4
  - h5netcdf
  - matplotlib
  - cmocean
  - dask
  - distributed>=2022.9.2
  - dask-jobqueue
  - zarr
  - jupyterlab
  - tqdm
  - memory_profiler
  - pip:
    - SALib
    - sshuttle
