name: thermal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - anaconda
  - pint
  - scipy
  - numpy
  - pandas
  - seaborn
  - pip
  - xarray = 0.19.0
  - matplotlib
  - pip:
    - SALib
